version: '3.7'

services:
  origin:
    build: .
    container_name: satta_wev
    ports:
    - "3000:3000/tcp"
    # environment:
#     networks:
#       myipvlan:
#         ipv4_address: 192.168.0.13

# networks:
#   myipvlan:
#     external: true
#     name: br0